### ISSUE TITLE
Please don't used our logos

### ISSUE THREAD

**Issue by CodeAndWeb** [snkkid99/SpriteSheetImporter_godot_plugin#1]
Hi,

you are using our original TexturePacker logos in your plugin - without our permission.
This is very confusing in the Godot Asset Library.
Please don't use our logos. Thanks.

Andreas from CodeAndWeb

**Comment by akien-mga** [comment]
I've changed the logo used on https://godotengine.org/asset-library/asset/201 for now until @snkkid99 can provide an alternative. The [`icon.png`](https://github.com/snkkid99/SpriteSheetImporter_godot_plugin/blob/master/addons/SpriteSheetImporter/icon.png) included in the repository should still be replaced though.

**Comment by CodeAndWeb** [comment]
Thanks.

**Comment by snkkid99** [comment]
done
